### ISSUE TITLE
Implement an address comparator that uses italian invoiceable fields

### ISSUE THREAD

**Issue by mmenozzi** [webgriffe/SyliusItalianInvoiceableOrderPlugin#1]

**Comment by lruozzi9** [comment]
I think we could close this issue, the comparator has been done [here](https://github.com/webgriffe/SyliusItalianInvoiceableOrderPlugin/blob/d2f236eaf0252ee41c4bcb0af11718f482f07ba3/src/Comparator/ItalianInvoiceableAddressComparatorDecorator.php).

**Comment by mmenozzi** [comment]
Ok!
