### ISSUE TITLE
Support for sylius 1.10

### ISSUE THREAD

**Issue by fabianobonomini** [webgriffe/SyliusItalianInvoiceableOrderPlugin#7]
Hi everyone!

I tried to install this plugin on version 1.10. but it seems not supported.

`Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for webgriffe/sylius-italian-invoiceable-order-plugin ^0.5.2 -> satisfiable by webgriffe/sylius-italian-invoiceable-order-plugin[0.5.2].
    - webgriffe/sylius-italian-invoiceable-order-plugin 0.5.2 requires sylius/sylius ~1.8.0 || ~1.9.0 -> satisfiable by sylius/sylius[1.8.x-dev, 1.9.x-dev, v1.8.0, v1.8.0-RC.1, v1.8.1, v1.8.10, v1.8.11, v1.8.12, v1.8.2, v1.8.3, v1.8.4, v1.8.5, v1.8.6, v1.8.7, v1.8.8, v1.8.9, v1.9.0, v1.9.0-ALPHA.1, v1.9.0-ALPHA.2, v1.9.0-BETA.1, v1.9.0-BETA.2, v1.9.0-BETA.3, v1.9.0-RC.1, v1.9.0-RC.2, v1.9.1, v1.9.2, v1.9.3, v1.9.4, v1.9.5, v1.9.6, v1.9.7, v1.9.8, v1.9.9] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.
`

Thanks
Have a nice one

**Comment by lruozzi9** [comment]
Hi @fabianobonomini! Yes, we need to update this plugin to support Sylius v1.9, v1.10, PHP 8.0, and drop the v1.8 support. Probably we will do this update within the next week. If you need it before, feel free to provide a PR and we will review it. 
The changes to be made are reported in the diff between the version [1.9 and 1.10 of the Plugin Skeleton](https://github.com/Sylius/PluginSkeleton/compare/v1.9.0...1.10).

**Comment by fabianobonomini** [comment]
Thanks @lruozzi9 I'll wait for your version bump

**Comment by lruozzi9** [comment]
Hi @fabianobonomini, we have released the [v0.6.0](https://github.com/webgriffe/SyliusItalianInvoiceableOrderPlugin/releases/tag/0.6.0) which provide support for Sylius 1.10 and PHP 8.0!

**Comment by fabianobonomini** [comment]
Thanks @lruozzi9 ! I'll setup ASAP on the project
